### PR TITLE
show and enable fields in TEST mode issue 44

### PR DESCRIPTION
**Pull request by sachingrover211**
Fix for issue 44.

### CODE REVIEW

**Comment by jonwetzel** [comment]
@sachingrover211  Overall, this is much better than the current version, but still has some bugs.  The following are bugs reproducible in problem isle6:

In TEST and EDITOR mode:
- [ ] Can't edit the node type for the given correct parameters, functions, and accumulators
- [ ] Can't edit the equations for the given correct accumulators

In STUDENT and COACHED mode:
- [ ] Can edit the equation for given functions
- [ ] Can edit the value for given correct parameters
- [ ] Can edit the value for given correct accumulators

More general testing of problems without given nodes worked fine in all modes, and I was able to complete problems with given nodes in all four modes.

These five bugs are not as critical as the original so I think we can afford to merge this first, update the server after today's classes and then start to work on a new PR for the other five bugs.

**Comment by sachingrover211** [comment]
@jonwetzel For test and editor mode these were expected behaviors, and these are set by the author to be shown as is. So this was never made in a way to be editable. Hence you see the two bugs.

I think in this bug the only bug is that the given complete correct nodes are leaving something editable. Which I think was the initial behavior as suggested by Kurt. We should probably ask him what he thinks is needed for this.

**Comment by sachingrover211** [comment]
I mean the initial behavior by Kurt was to leave nothing editable for the complete nodes that are given to the students.

**Comment by jonwetzel** [comment]
@sachingrover211  When we found the bug I checked with Kurt and he said he wanted TEST and EDITOR to have all parts of the given node unlocked, but initialized to the state the author left the given node in.  I don't think he knew that was a new feature, but it sounds like it is!  (So those two "bugs" will move to a new task.)

The complete correct nodes shouldn't leave something editable in COACHED and STUDENT mode.  That doesn't happen on the live version, so it must be a side effect of this one-line change.  Please attempt a fix.

**Comment by sachingrover211** [comment]
Cool I will have to see what to do for that as it might be a big change for the new task.

Ok. Let me check the bug in Student and Coached mode why is that happening. Thanks.

**Comment by jonwetzel** [comment]
@sachingrover211 Yeah I think the new task will end up further down the backlog....  The topomath node editor refactor will be your next priority after this fix is in.  Thanks!

**Comment by jonwetzel** [comment]
New fix works great on isle6.  We'll merge and pull to server and try it on Kurt's problems too.

The other part of the fix has been moved to a new task: https://github.com/Dragoon-Lab/LaitsV3/issues/49

**Pull request merged**
